name = "temporal-conductance-and-bounds-on-the-voter-model-for-dynamic-networks"
version = "0.1.0"
defaultTargets = ["SimpleGraph", "Probability", "TemporalGraph", "VoterProcess", "UpperBound", "LowerBound", "VoterModel"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.docstringPosition = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.31.0"

[[lean_lib]]
name = "SimpleGraph"

[[lean_lib]]
name = "Probability"

[[lean_lib]]
name = "TemporalGraph"

[[lean_lib]]
name = "VoterProcess"

[[lean_lib]]
name = "UpperBound"

[[lean_lib]]
name = "LowerBound"

[[lean_lib]]
name = "VoterModel"
