module

public import VoterProcess.Absorption.Time
public import VoterProcess.TwoOpinion
public import UpperBound.EmbeddedChain
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Arctan
import Mathlib.MeasureTheory.Covering.Besicovitch



@[expose] public section
open MeasureTheory ProbabilityTheory
open scoped BigOperators

noncomputable section

namespace VoterModel

variable {V : Type*} [Fintype V] [Nonempty V] [DecidableEq V]

/-! ## Main results

Conditional (fiber-restricted) `VoterModel` and embedded-chain time bounds:
`conditionalVoterModel`, `conditionalVoterModel_compat`, `subtype_filtration_eq`,
`embeddedChainTime_le_sum_early`, `embeddedChainTime_le_sum_tight`. -/

/-!
### Auxiliary: conditional VoterModel and fiber-conditional absorption

T22 (`upper_bound`) is proved by a total-probability averaging argument over
initial opinion sets `σ₀ : Finset V`.  For each `σ₀`, we construct a
`TemporalGraph.VoterModelAbstract` on the subtype `{ω | vm.opinionZeroSet 0 ω = σ₀}` and apply
T23 (`voter_absorb_two_opinion`).  The subtype VoterModel inherits all
pointwise fields from `vm`; the only nontrivial fields are `markovMarginal` and
`markovProperty`, whose proofs require an induction using `vm.A_markovProperty`.
These are deferred here.
-/

-- ---------------------------------------------------------------------------
-- Private helpers for cond_fiber_absorption
-- ---------------------------------------------------------------------------
-- The iterated Markov property `multistep_markov_filtration₂` used below now
-- lives in `VoterModel.Proof.DeterministicFiber` (made public there so it can
-- be shared between L58 and this file).

/-- The σ-algebra on the subtype `↥E` generated by `A 0, …, A t` equals the
comap of the ambient filtration `vm.ℱ t` under `Subtype.val`. -/
private theorem subtype_filtration_eq
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (E : Set Ω) (t : ℕ) :
    (⨆ j ∈ Finset.Iic t,
      MeasurableSpace.comap (fun ω' : ↥E => vm.opinionZeroSet j ω'.val) ⊤) =
    MeasurableSpace.comap (Subtype.val : ↥E → Ω) (vm.ℱ t) := by
  -- vm.ℱ t = ⨆ j ∈ Iic t, comap (vm.opinionZeroSet j) ⊤
  -- vm.ℱ t = ⨆ j ∈ Iic t, comap (vm.opinionZeroSet j) ⊤ (by rfl)
  -- Rewrite fun ω' => vm.opinionZeroSet j ω'.val as vm.opinionZeroSet j ∘ Subtype.val, then use comap_comp
  simp_rw [show ∀ j, (fun ω' : ↥E => vm.opinionZeroSet j ω'.val) = vm.opinionZeroSet j ∘ Subtype.val from fun _ => rfl,
    ← MeasurableSpace.comap_comp]
  -- Now: ⨆ j ∈ Iic t, comap Subtype.val (comap (vm.opinionZeroSet j) ⊤) = comap Subtype.val (↑vm.ℱ t)
  rw [vm.fseq_eq_A t]
  simp_rw [MeasurableSpace.comap_iSup]

noncomputable def conditionalVoterModel
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (σ₀ : Finset V) (hpos : (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀} ≠ 0) :
    TemporalGraph.VoterModelAbstract G 2 ↥{ω | vm.opinionZeroSet 0 ω = σ₀} :=
  TemporalGraph.VoterModelAbstract.ofOpinionZeroData
    ⟨Measure.comap Subtype.val (ProbabilityTheory.cond (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀}), by
      have hE_meas : MeasurableSet {ω : Ω | vm.opinionZeroSet 0 ω = σ₀} :=
        vm.A_meas 0 _ ⟨{σ₀}, trivial, by ext; simp⟩
      constructor
      rw [comap_subtype_coe_apply hE_meas _ Set.univ]
      simp only [Set.image_univ, Subtype.range_coe_subtype]
      rw [ProbabilityTheory.cond_apply hE_meas]
      simp only [Set.setOf_mem_eq, Set.inter_self]
      exact ENNReal.inv_mul_cancel hpos (measure_ne_top _ _)⟩
    (fun t ω' => vm.opinionZeroSet t ω'.val)
    (fun t => by
      -- Need: comap (fun ω' => vm.opinionZeroSet t ω'.val) ⊤ ≤ (subtype measurable space on ↥E)
      -- Subtype measurable space = comap Subtype.val mΩ
      -- By comap_comp: comap (vm.opinionZeroSet t ∘ Subtype.val) ⊤ = comap Subtype.val (comap (vm.opinionZeroSet t) ⊤)
      -- Then comap_mono + vm.A_meas t gives the result
      show MeasurableSpace.comap (vm.opinionZeroSet t ∘ Subtype.val) ⊤ ≤ MeasurableSpace.comap Subtype.val mΩ
      rw [← MeasurableSpace.comap_comp]
      exact MeasurableSpace.comap_mono (vm.A_meas t))
    (fun t S' B' hB' => by
      have hE_meas : MeasurableSet {ω : Ω | vm.opinionZeroSet 0 ω = σ₀} :=
        vm.A_meas 0 _ ⟨{σ₀}, trivial, by ext; simp⟩
      simp only [ProbabilityMeasure.coe_mk]
      -- Rewrite the subtype filtration: ℱ' t = comap Subtype.val (vm.ℱ t)
      rw [subtype_filtration_eq G vm {ω | vm.opinionZeroSet 0 ω = σ₀} t] at hB'
      rw [MeasurableSpace.measurableSet_comap] at hB'
      obtain ⟨u, hu_meas, hu_eq⟩ := hB'
      -- Subtype.val '' B' = u ∩ E
      have hImg_eq : Subtype.val '' B' = u ∩ {ω | vm.opinionZeroSet 0 ω = σ₀} := by
        rw [← hu_eq]; ext ω; simp [and_comm]
      have hE_filt : @MeasurableSet Ω (vm.ℱ t) {ω | vm.opinionZeroSet 0 ω = σ₀} :=
        vm.measurableSet_setOf_A_eq (Nat.zero_le t) σ₀
      have hImg_meas : @MeasurableSet Ω (vm.ℱ t) (Subtype.val '' B') := by
        rw [hImg_eq]; exact hu_meas.inter hE_filt
      -- vm.A_markovProperty applied to Subtype.val '' B'
      have hvm := vm.A_markovProperty t S' (Subtype.val '' B') (vm.fmeas_to_Asup hImg_meas)
      -- LHS: μ'(B' ∩ {A(t+1)=S'})
      --     = (vm.μ : Measure Ω)[|E](↑''B' ∩ {A(t+1)=S'})            [comap_subtype_coe_apply + image of inter]
      --     = (μ E)⁻¹ * μ(↑''B' ∩ {A(t+1)=S'})          [cond_apply + ↑''B' ⊆ E]
      -- RHS: ∫⁻ ω' in B', stepDist₂ ∂μ'
      --     = ∫⁻ ω in ↑''B', stepDist₂ ∂((vm.μ : Measure Ω)[|E])       [setLIntegral_subtype]
      --     = (μ E)⁻¹ * ∫⁻ ω in ↑''B', stepDist₂ ∂vm.μ   [cond = smul + lintegral_smul + ↑''B' ⊆ E]
      --     = (μ E)⁻¹ * μ(↑''B' ∩ {A(t+1)=S'})          [hvm backwards]
      -- Rewrite LHS
      rw [comap_subtype_coe_apply hE_meas]
      rw [show Subtype.val '' (B' ∩ {ω' | vm.opinionZeroSet (t + 1) ω'.val = S'}) =
            Subtype.val '' B' ∩ {ω | vm.opinionZeroSet (t + 1) ω = S'} from by
          ext ω; simp only [Set.mem_image, Set.mem_inter_iff, Set.mem_setOf_eq]
          constructor
          · rintro ⟨x, ⟨hxB, hxS⟩, rfl⟩; exact ⟨⟨x, hxB, rfl⟩, hxS⟩
          · rintro ⟨⟨x, hxB, rfl⟩, hxS⟩; exact ⟨x, ⟨hxB, hxS⟩, rfl⟩]
      rw [ProbabilityTheory.cond_apply hE_meas]
      rw [show {ω : Ω | vm.opinionZeroSet 0 ω = σ₀} ∩ (Subtype.val '' B' ∩ {ω | vm.opinionZeroSet (t + 1) ω = S'}) =
            Subtype.val '' B' ∩ {ω | vm.opinionZeroSet (t + 1) ω = S'} from by
          have hsub : Subtype.val '' B' ⊆ {ω : Ω | vm.opinionZeroSet 0 ω = σ₀} := Subtype.coe_image_subset _ B'
          ext ω; simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
          constructor
          · rintro ⟨_, h1, h2⟩; exact ⟨h1, h2⟩
          · rintro ⟨h1, h2⟩; exact ⟨hsub h1, h1, h2⟩]
      -- Now goal: (μ E)⁻¹ * μ(↑''B' ∩ {A(t+1)=S'}) = ∫⁻ x in ↑''B', stepDist₂... ∂(vm.μ : Measure Ω)[|E]
      -- Rewrite RHS: setLIntegral_subtype + cond expansion + hvm backwards
      rw [setLIntegral_subtype hE_meas B' (fun ω => (VoterModel.stepDist₂ G t (vm.opinionZeroSet t ω)) S')]
      rw [ProbabilityTheory.cond, setLIntegral_smul_measure, smul_eq_mul]
      -- ∫⁻ x in ↑''B', f x ∂((vm.μ : Measure Ω).restrict E) = ∫⁻ x in ↑''B', f x ∂vm.μ  [↑''B' ⊆ E]
      -- We have: ((vm.μ : Measure Ω).restrict E).restrict (↑''B') = (vm.μ : Measure Ω).restrict (↑''B' ∩ E) = (vm.μ : Measure Ω).restrict (↑''B')
      have hImg_meas_plain : MeasurableSet (Subtype.val '' B') := vm.ℱ.le t _ hImg_meas
      congr 1
      rw [show ∫⁻ x in Subtype.val '' B', (VoterModel.stepDist₂ G t (vm.opinionZeroSet t x)) S'
                ∂(vm.μ : Measure Ω).restrict {ω | vm.opinionZeroSet 0 ω = σ₀} =
              ∫⁻ x in Subtype.val '' B', (VoterModel.stepDist₂ G t (vm.opinionZeroSet t x)) S' ∂vm.μ from by
          simp only [Measure.restrict_restrict hImg_meas_plain]
          rw [Set.inter_comm,
              Set.inter_eq_right.mpr (Subtype.coe_image_subset _ B')]]
      exact hvm)

/-- The opinion-0 set of the conditional model is the base model's, restricted. -/
@[simp] theorem conditionalVoterModel_A
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (σ₀ : Finset V) (hpos : (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀} ≠ 0)
    (t : ℕ) (ω' : ↥{ω | vm.opinionZeroSet 0 ω = σ₀}) :
    (conditionalVoterModel G vm σ₀ hpos).opinionZeroSet t ω' = vm.opinionZeroSet t ω'.val :=
  VoterModel.phiZero_phiZeroInv (vm.opinionZeroSet t ω'.val)

/-- The (coerced) measure of the conditional model is the conditioned measure. -/
@[simp] theorem conditionalVoterModel_μ_coe
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (σ₀ : Finset V) (hpos : (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀} ≠ 0) :
    ((conditionalVoterModel G vm σ₀ hpos).μ : Measure ↥{ω | vm.opinionZeroSet 0 ω = σ₀}) =
      Measure.comap Subtype.val
        (ProbabilityTheory.cond (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀}) :=
  rfl

theorem conditionalVoterModel_compat
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (σ₀ : Finset V) (hpos : (vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀} ≠ 0) (K : ℕ) :
    ((vm.μ : Measure Ω) {ω | vm.opinionZeroSet 0 ω = σ₀}).toReal *
      (((conditionalVoterModel G vm σ₀ hpos).μ : Measure _)
        {ω' : ↥{ω | vm.opinionZeroSet 0 ω = σ₀} |
          (conditionalVoterModel G vm σ₀ hpos).absorptionTime ω' ≤ (K : ℕ∞)}).toReal =
    ((vm.μ : Measure Ω) ({ω | vm.opinionZeroSet 0 ω = σ₀} ∩ {ω | vm.absorptionTime ω ≤ (K : ℕ∞)})).toReal := by
  have hE_meas : MeasurableSet {ω : Ω | vm.opinionZeroSet 0 ω = σ₀} :=
    vm.A_meas 0 _ ⟨{σ₀}, trivial, by ext; simp⟩
  -- The conditional model's absorption time agrees with the base model's,
  -- since `(conditionalVoterModel …).opinionZeroSet s ω' = vm.opinionZeroSet s ω'.val` definitionally.
  have hAT : ∀ ω' : ↥{ω | vm.opinionZeroSet 0 ω = σ₀},
      (conditionalVoterModel G vm σ₀ hpos).absorptionTime ω' = vm.absorptionTime ω'.val :=
    fun ω' => TemporalGraph.VoterModelAbstract.absorptionTime_eq_of_minoritySet_eq
      (conditionalVoterModel G vm σ₀ hpos) vm ω' ω'.val
      (fun t => by rw [conditionalVoterModel_A])
  simp only [hAT]
  -- Unfold μ'
  simp only [conditionalVoterModel_μ_coe]
  -- μ'(absorptionTime ≤ K) = ((vm.μ : Measure Ω)[|E]).comap Subtype.val {absorptionTime ≤ K}
  --               = (vm.μ : Measure Ω)[|E] (Subtype.val '' {absorptionTime ≤ K})
  --               = (vm.μ : Measure Ω)[|E] (E ∩ {absorptionTime ≤ K})
  rw [comap_subtype_coe_apply hE_meas]
  rw [show Subtype.val '' {ω' : ↥{ω | vm.opinionZeroSet 0 ω = σ₀} | vm.absorptionTime ω'.val ≤ (K : ℕ∞)} =
        {ω | vm.opinionZeroSet 0 ω = σ₀} ∩ {ω | vm.absorptionTime ω ≤ (K : ℕ∞)} from by
      ext ω; simp only [Set.mem_image, Set.mem_inter_iff, Set.mem_setOf_eq]
      constructor
      · rintro ⟨x, hxle, rfl⟩; exact ⟨x.property, hxle⟩
      · rintro ⟨hmem, hle⟩; exact ⟨⟨ω, hmem⟩, hle, rfl⟩]
  -- (vm.μ : Measure Ω)[|E](E ∩ {abs ≤ K}) = (μ E)⁻¹ * μ(E ∩ (E ∩ {abs ≤ K}))
  rw [ProbabilityTheory.cond_apply hE_meas]
  rw [show {ω | vm.opinionZeroSet 0 ω = σ₀} ∩ ({ω | vm.opinionZeroSet 0 ω = σ₀} ∩ {ω | vm.absorptionTime ω ≤ (K : ℕ∞)}) =
        {ω | vm.opinionZeroSet 0 ω = σ₀} ∩ {ω | vm.absorptionTime ω ≤ (K : ℕ∞)} from by ext; simp]
  -- Goal: μ(E).toReal * ((μ E)⁻¹ * μ(E ∩ {abs ≤ K})).toReal = μ(E ∩ {abs ≤ K}).toReal
  rw [ENNReal.toReal_mul, ENNReal.toReal_inv]
  field_simp [ENNReal.toReal_ne_zero.mpr ⟨hpos, measure_ne_top _ _⟩]

/-- Bound `T_i ω ≤ ∑_{j < i+1} Δ_j`. Used by L51 helpers below; the original
proof of this lemma lives later in the file but is moved here for visibility. -/
lemma embeddedChainTime_le_sum_early
    {Ω : Type*} [MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (Δ : ℕ → ℕ) (hΔ_pos : ∀ j, 1 ≤ Δ j) (i : ℕ) (ω : Ω) :
    embeddedChainTime G vm Δ i ω ≤ ∑ j ∈ Finset.range (i + 1), Δ j := by
  induction i with
  | zero => simp [embeddedChainTime]
  | succ i' _ =>
    simp only [embeddedChainTime]
    have h := volumeExcursionTime_le_succ G vm (embeddedChainTime G vm Δ i' ω)
      ((∑ j ∈ Finset.range (i' + 1), Δ j) - 1) ω
    have h_pos : 1 ≤ ∑ j ∈ Finset.range (i' + 1), Δ j := by
      have h0 : Δ 0 ≤ ∑ j ∈ Finset.range (i' + 1), Δ j :=
        Finset.single_le_sum (f := Δ) (fun _ _ => Nat.zero_le _)
          (Finset.mem_range.mpr (by omega))
      exact le_trans (hΔ_pos 0) h0
    have hsub : (∑ j ∈ Finset.range (i' + 1), Δ j) - 1 + 1 =
        ∑ j ∈ Finset.range (i' + 1), Δ j := Nat.sub_add_cancel h_pos
    have h' : volumeExcursionTime G vm (embeddedChainTime G vm Δ i' ω)
        ((∑ j ∈ Finset.range (i' + 1), Δ j) - 1) ω ≤
        ∑ j ∈ Finset.range (i' + 1), Δ j := by
      rw [← hsub]; exact h
    have hmono : ∑ j ∈ Finset.range (i' + 1), Δ j ≤
        ∑ j ∈ Finset.range (i' + 1 + 1), Δ j :=
      Finset.sum_le_sum_of_subset (Finset.range_subset_range.mpr (by omega))
    exact h'.trans hmono

/-- Tight bound `T_i ω ≤ ∑_{j < i} Δ_j`. Strictly stronger than
`embeddedChainTime_le_sum_early` (which gives `T_i ω ≤ ∑_{j < i+1} Δ_j`).
Used to derive the cap hypothesis `T_i ≤ (∑_{j < i+1} Δ_j) - 1` at the tight
form, since `T_i ≤ ∑_{j < i} Δ_j` and `1 ≤ Δ_i` give `T_i + 1 ≤ ∑_{j < i+1} Δ_j`. -/
lemma embeddedChainTime_le_sum_tight
    {Ω : Type*} [MeasurableSpace Ω]
    (G : TemporalGraph V) (vm : TemporalGraph.VoterModelAbstract G 2 Ω)
    (Δ : ℕ → ℕ) (hΔ_pos : ∀ j, 1 ≤ Δ j) (i : ℕ) (ω : Ω) :
    embeddedChainTime G vm Δ i ω ≤ ∑ j ∈ Finset.range i, Δ j := by
  induction i with
  | zero => simp [embeddedChainTime]
  | succ i' _ =>
    simp only [embeddedChainTime]
    have h := volumeExcursionTime_le_succ G vm (embeddedChainTime G vm Δ i' ω)
      ((∑ j ∈ Finset.range (i' + 1), Δ j) - 1) ω
    have h_pos : 1 ≤ ∑ j ∈ Finset.range (i' + 1), Δ j := by
      have h0 : Δ 0 ≤ ∑ j ∈ Finset.range (i' + 1), Δ j :=
        Finset.single_le_sum (f := Δ) (fun _ _ => Nat.zero_le _)
          (Finset.mem_range.mpr (by omega))
      exact le_trans (hΔ_pos 0) h0
    omega


end VoterModel
